#! /bin/sh

#    ____ ____  ______        ____  __ 
#   | __ ) ___||  _ \ \      / /  \/  |  - z0mbi3
#   |  _ \___ \| |_) \ \ /\ / /| |\/| |  - https://github.com/gh0stzk/dotfiles
#   | |_) |__) |  __/ \ V  V / | |  | |  - z0mbi3.zk@protonmail.com
#   |____/____/|_|     \_/\_/  |_|  |_|
#                                    z0mbi3 config..


bash $HOME/.config/bspwm/autostart.sh &

# Def vars
export RICETHEME=$(<$HOME/.config/bspwm/rice.cfg)
PATH="$HOME/.config/bspwm/scripts:$PATH"

# Workspaces
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d 1 2 3 4 5 6 7 8 9 10
		let name++
	done
}
workspaces

# Launch The Rice!!
source LaunchWorld
SetGirlFriendRice
AutoStartApps

# --- BSPWM configuration ---

# import
bspc config external_rules_command ~/.config/bspwm/scripts/external_rules

# window
bspc config window_gap                 10    # space between windows
# bspc config border_radius            8
bspc config border_width               2    # width of windows border

bspc config split_ratio                0.5  # each new window use half of parent space

# padding
# bspc config top_padding              30
# bspc config bottom_padding           0
# bspc config left_padding             0
# bspc config right_padding            0

# monocle
bspc config single_monocle             true
bspc config borderless_monocle         false
bspc config gapless_monocle            false

# focus
# bspc config focus_by_distance        true
bspc config focus_follows_pointer      false
# bspc config history_aware_focus      true

# pointer
# bspc config click_to_focus           true
bspc config focus_follows_pointer      false
bspc config pointer_modifier           mod4 
bspc config pointer_action1            move 
bspc config pointer_action2            resize_side 
bspc config pointer_action3            resize_corner

bspc config center_pseudo_tiled			   true

bspc config automatic_scheme           longest_side
bspc config initial_polarity           second_child

bspc config remove_disabled_monitors   true 
bspc config merge_overlapping_monitors true

bspc config pointer_motion_interval    16

#BSPWM coloring
gray="#595f6f"
red="#fc5d7c"
magenta="#b39df3"

bspc config normal_border_color		$gray
bspc config active_border_color		$magenta
bspc config focused_border_color	$red
bspc config presel_feedback_color	$magenta
#bspc config urgent_border_color 	"#dd2727"

